#!/bin/sh
#
# websockify   This shell script takes care of starting and stopping
#              the websockify server.
#
# chkconfig: 2345 90 10
# description: websockify server.
# processname: websockify
# pidfile: /var/websockify/websockify.pid

# Installation instructions:
# cp init.d/websockify /etc/init.d/websockify
# chkconfig --add websockify
# service websockify start

# Source function library.
. /etc/rc.d/init.d/functions

BINDIR=/usr/bin
VARDIR=/var/run
WEBSOCKIFY=$BINDIR/websockify
WEBSOCKIFY_PORT1=3011
WEBSOCKIFY_PORT2=3012
WEBSOCKIFY_PORT3=3013
LOCAL_ADDRESS1=127.0.0.1:3001
LOCAL_ADDRESS2=127.0.0.1:3002
LOCAL_ADDRESS3=127.0.0.1:3003
#PIDFILE=$VARDIR/websockify.pid
USER=websockify

# See how we were called.
case "$1" in
  start)
	[ -x $WEBSOCKIFY ] || exit 1
	echo -n $"Starting websockify server: "
	#cd $VARDIR && daemon --user "$USER" --pidfile $PIDFILE "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT" "$LOCAL_ADDRESS"
	#cd $VARDIR && daemon --user "$USER" "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT1" "$LOCAL_ADDRESS1"
	#cd $VARDIR && daemon --user "$USER" "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT2" "$LOCAL_ADDRESS2"
	#cd $VARDIR && daemon --user "$USER" "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT3" "$LOCAL_ADDRESS3"
	nohup "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT1" "$LOCAL_ADDRESS1" >& /dev/null &
	nohup "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT2" "$LOCAL_ADDRESS2" >& /dev/null &
	nohup "$WEBSOCKIFY" :"$WEBSOCKIFY_PORT3" "$LOCAL_ADDRESS3" >& /dev/null &
	nohupPid=$!
	wait $nohupPid
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/websockify
	;;
  stop)
	# Stop daemon.
	echo -n $"Shutting down websockify server: "
	killproc websockify
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/websockify
	;;
  status)
	status websockify
	RETVAL=$?
	;;
  restart|reload)
	$0 stop
	$0 start
	;;
  condrestart)
	[ -f /var/lock/subsys/websockify ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=3
	;;
esac

exit $RETVAL
